name: Submit a new Idea
description: Add an original research Idea to the public library
title: "[NEW IDEA] "
body:
  - type: input
    id: idea_title
    attributes:
      label: Idea title
      description: Give your research Idea a short title.
    validations:
      required: true
  - type: textarea
    id: idea_description
    attributes:
      label: Idea description
      description: Describe the key research Idea. This can be brief or detailed.
    validations:
      required: true
  - type: textarea
    id: ai_prompt
    attributes:
      label: Optional prompt for AI
      description: If you have a core prompt or instructions for AI, add them here.
    validations:
      required: false
  - type: checkboxes
    id: declaration
    attributes:
      label: Declaration
      options:
        - label: I genuinely believe this core Idea is my own original research Idea and is not already publicly disclosed in the academic literature.
          required: true
        - label: I have the right to publish the content I submit.
          required: true
